# -*- coding: utf-8 -*-
"""vectordb_chroma_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJke5KqkU1_rKzsyefEd_rzJ5bamcRvR
"""

pip install chromadb

import chromadb

chroma_client=chromadb.Client()

collection=chroma_client.get_or_create_collection(name="my_documents")

collection.add(
   documents= [
       "This is a document about pineapple",
       "This is a document about banana",
       "This is a document about apple",
       "This is a document about orange",
       "This is a document about peach",
       "This is a document about watermelon",
       "This is a document about grapes",
       "This is a document about melon",
       "This is a document about strawberry",
       "This is a document about kiwi",
       "This is a document about mango",
   ] ,
   ids=["id1","id2", "id3","id4","id5", "id6","id7","id8", "id9","id10","id11"]
)

results = collection.query(
    query_texts=["This is a query document about the climate, agriculture and nature of Africa, which one of the fruits is expected to be found there most ?"], # Chroma will embed this for you
    n_results=3 # how many results to return
)
print(results)